#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAMSATPLCFX3G
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FX3G-SQL")]
	public partial class report_excelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public report_excelDataContext() : 
				base(global::GIAMSATPLCFX3G.Properties.Settings.Default.FX3G_SQLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public report_excelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public report_excelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public report_excelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public report_excelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FX3GA_Data> FX3GA_Datas
		{
			get
			{
				return this.GetTable<FX3GA_Data>();
			}
		}
		
		public System.Data.Linq.Table<FX3GA_Data1> FX3GA_Data1s
		{
			get
			{
				return this.GetTable<FX3GA_Data1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FX3GA_Data")]
	public partial class FX3GA_Data
	{
		
		private System.Nullable<System.DateTime> _date_time;
		
		private System.Nullable<int> _data_Integer;
		
		private string _data_Text;
		
		private System.Nullable<double> _data_Real;
		
		public FX3GA_Data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_Integer", DbType="Int")]
		public System.Nullable<int> data_Integer
		{
			get
			{
				return this._data_Integer;
			}
			set
			{
				if ((this._data_Integer != value))
				{
					this._data_Integer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_Text", DbType="NVarChar(MAX)")]
		public string data_Text
		{
			get
			{
				return this._data_Text;
			}
			set
			{
				if ((this._data_Text != value))
				{
					this._data_Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_Real", DbType="Float")]
		public System.Nullable<double> data_Real
		{
			get
			{
				return this._data_Real;
			}
			set
			{
				if ((this._data_Real != value))
				{
					this._data_Real = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[FX3GA-Data]")]
	public partial class FX3GA_Data1
	{
		
		private System.Nullable<System.DateTime> _date_time;
		
		private System.Nullable<int> _data_Integer;
		
		private string _data_Text;
		
		private System.Nullable<double> _data_Real;
		
		public FX3GA_Data1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_Integer", DbType="Int")]
		public System.Nullable<int> data_Integer
		{
			get
			{
				return this._data_Integer;
			}
			set
			{
				if ((this._data_Integer != value))
				{
					this._data_Integer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_Text", DbType="NVarChar(MAX)")]
		public string data_Text
		{
			get
			{
				return this._data_Text;
			}
			set
			{
				if ((this._data_Text != value))
				{
					this._data_Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_Real", DbType="Float")]
		public System.Nullable<double> data_Real
		{
			get
			{
				return this._data_Real;
			}
			set
			{
				if ((this._data_Real != value))
				{
					this._data_Real = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
